# Generated by Django 2.0.7 on 2018-07-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('User_Name', models.CharField(error_messages={'unique': 'User Name already exist'}, max_length=50, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'e-mail already exist'}, max_length=50, unique=True)),
                ('Address', models.CharField(max_length=150)),
                ('contact', models.CharField(error_messages={'unique': 'PhoneNumber already exist'}, max_length=11, unique=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1)),
                ('Age', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
