# Generated by Django 2.0.7 on 2018-07-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20180717_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field='hight', upload_to='image/', width_field='width'),
        ),
    ]
