# Generated by Django 2.0.7 on 2018-07-18 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20180717_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='T_shirt_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shirt_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shoe_size',
        ),
    ]
